### ISSUE TITLE
Settings window can be resized beyond normal minimum width, text in settings menu under "sharing" doesn't wrap.

### ISSUE THREAD

**Issue by DannyJJK** [ProgressBox/Mac#4]
<img width="512" alt="screenshot 2019-01-25 at 10 09 15" src="https://user-images.githubusercontent.com/11057501/51739413-4a42a200-2089-11e9-84ad-b8cbc34ef09c.png">

I haven't purchased the application (yet!) so I'm still in trial mode. Settings window can be resized beyond normal minimum width, causing text to overlap. 

<img width="876" alt="screenshot 2019-01-25 at 10 10 05" src="https://user-images.githubusercontent.com/11057501/51739508-8544d580-2089-11e9-9faa-af5f68460900.png">

In addition, the text under "Sharing" is not wrapped, so it is cut off at the end.

**Comment by cliftonlabrum** [comment]
Great catch! Thank you! 👍 

This will be fixed in version `1.0.5` coming soon to the App Store. 🙂
