### ISSUE TITLE
Creating a new task with one already selected, shows both tasks "selected with blue outline" when clicking on newly created one

### ISSUE THREAD

**Issue by DannyJJK** [ProgressBox/Mac#5]
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/11057501/51837508-7a917700-22fb-11e9-8f2e-ce33bd09f459.png">

I had "test paid service integration" selected, then created the task "test" and selected that, which resulted in both tasks having the "blue outline".

**Comment by cliftonlabrum** [comment]
Fixed in `1.0.5`.
