### ISSUE TITLE
Deleting a comment so that there are no comments left, doesn't show the usual "No comments" text

### ISSUE THREAD

**Issue by DannyJJK** [ProgressBox/Mac#7]
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/11057501/51838448-2fc52e80-22fe-11e9-8e7c-e3c589bf3734.png">

I'm not sure whether this is a bug, but if you delete all the comments so there are none left, I would expect that it would return to saying "No comments" text, however the area just remains empty. Clicking on a different task and then back onto the task shows the "No comments" text again as you can see here:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/11057501/51838521-69963500-22fe-11e9-9797-474d17210c70.png">

**Comment by cliftonlabrum** [comment]
Fixed in `1.0.5`. Thank you!
